spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac_demo?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 127.0.0.1
    # 连接超时时间（毫秒）
    timeout: 0
    port: 6379
    # Redis 数据库索引（默认为 0）
    database: 0
    # Redis 服务器连接端口
    # Redis 服务器连接密码（默认为空）
    password: password
    #连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
hust:
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: Authorization
logging.level.com.hust.rbacbackend.mapper: debug
